config/routes.rb
EMS::Application.routes.draw do

  resources :users
  resources :pcrs

  root 'site#index'

  get 'login' => 'session#new'
  post 'login'=> 'session#create'
  delete 'logout' => 'session#destroy'
  get 'logout' => 'session#destroy'

  get 'privacy' => 'site#privacy'
  get 'terms'=> 'site#terms'

  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  # get 'squad' => 'members#index'

  # get 'register' => 'members#new'
  # post 'register' => 'members#create'

  # get 'members/:user_id' => 'members#show', as: :member

  # get 'pcr' => 'pcr#index'

  # get 'pcr' => 'pcr#new'
  # post 'pcr' => 'pcr#create'


  # put 'squad/edit/:user_id' => 'members#update'
  # patch 'squad/edit/:user_id' => 'members#update'
  # delete 'squad/:user_id' => 'members#destroy'


  # resources :user do
  #   get :avatar, on: :member
  # end
 
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  # skip_before_action :verify_authenticity_token

  def new
    # @messages = flash.inspect
    # @messages = flash.map {| key, value| "#{key.capitalize}: #{value}"}.join(";")
    # render text: "Display the log in form."
    redirect_to root_url, notice: "You are logged in." if current_user
  end

  def create
    
    if params[:user][:password].blank?
      #password reset flow
      PasswordResetter.new(flash).handle_reset_request(user_params)
    
    else
      #authenticate password flow
      return if log_user_in( UserAuthenticator.new(session,flash).authenticate_user(user_params) )
    end
    # (redirect_to root_url and return) if flash.empty?
    render :new
  end

  def destroy
    log_user_out(@user)
    # render text: "Log the user out."
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/views/session/new.html.slim
= form_for :user, url: login_url, html: { id: "login-form", :multipart => true } do |f|
  
  fieldset

    legend.legend Sign in
    .sign-up-link 
        = link_to "Sign up!", new_user_url, method: :get, class: "btn btn-default register-link"
        
    .form-group
      = f.label :email, class: "sr-only"
      = f.text_field :email, class: "form-control", placeholder: "email address"
    
    .form-group
      = f.label :password, class: "sr-only"
      = f.password_field :password, class: "form-control", placeholder: "password"

    .form-group
      =f.submit "Sign In", class: "btn btn-success btn-lg"