config/routes.rb
EMS::Application.routes.draw do

  resources :users
  resources :pcrs

  root 'site#index'

  get 'login' => 'session#new'
  post 'login'=> 'session#create'
  delete 'logout' => 'session#destroy'
  get 'logout' => 'session#destroy'

  get 'privacy' => 'site#privacy'
  get 'terms'=> 'site#terms'

  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  # get 'squad' => 'members#index'

  # get 'register' => 'members#new'
  # post 'register' => 'members#create'

  # get 'members/:user_id' => 'members#show', as: :member

  # get 'pcr' => 'pcr#index'

  # get 'pcr' => 'pcr#new'
  # post 'pcr' => 'pcr#create'


  # put 'squad/edit/:user_id' => 'members#update'
  # patch 'squad/edit/:user_id' => 'members#update'
  # delete 'squad/:user_id' => 'members#destroy'


  # resources :user do
  #   get :avatar, on: :member
  # end
 
end

app/models/user.rb
require 'bcrypt' 
 
PASSWORD_RESET_EXPIRES = 4

class User

  include Mongoid::Document
  include Mongoid::Timestamps

  extend CarrierWave::Mount
  
  attr_accessor :password, :password_confirmation, :image, :image_cache

  mount_uploader :image, ImageUploader


  field :email, type: String
  field :salt, type: String
  field :fish, type: String
  field :code, type: String
  field :expires_at, type: Time
  field :status, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :image, type: String


  before_save :set_random_password, :encrypt_password
  before_save :capitalize_names
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, confirmation: true
  validates :status, presence: true
  validates_inclusion_of :status, :in => ["vet", "rookie"]


  def self.register_user (params)
    # if params[:password].blank? 
    #   User.errors.add(:password, "fill in all of the fields.")
    # else
    user = User.create(params)
    user.store_image!
    user if user
    # end
  end

  def self.authenticate email, password
    user = User.find_by email: email
    user if user and user.authenticate(password)
  end

  def self.find_by_code code
    if user = User.find_by({:code => code, :expires_at => {"$gte" => Time.now.gmtime}})
      user.set_expiration
    end
    user
  end

  def self.find_by_id id
    if user = User.find_by({:id => id})
    end
    user
  end

  def authenticate password
    self.fish == BCrypt::Engine.hash_secret(password, self.salt)
  end


  def set_password_reset
    self.code = SecureRandom.urlsafe_base64
    set_expiration
  end

  def set_expiration
    self.expires_at = PASSWORD_RESET_EXPIRES.hours.from_now
    self.save
  end

  def reset_password(params)
    if params[:password].blank?
      self.errors.add(:password, "can't be blank")
      false
    else
      if self.update_attributes(params)
        self.update_attributes(params.merge( code: nil, expires_at: nil ))
      end
    end
  end

  def self.options_for_emt_vet
    @options = []
    @users = User.where(:status => 'vet')
    @options = @users.map { |user| [user.last_name] }

    @options
  end

  def self.options_for_emt_rookie
    @options = []
    @users = User.where(:status => 'rookie')
    @options = @users.map { |user| [user.last_name] }

    @options
  end

  protected

    def set_random_password
      if self.fish.blank? and password.blank?
        self.salt = BCrypt::Engine.generate_salt
        self.fish = BCrypt::Engine.hash_secret(SecureRandom.base64(32), self.salt)
      end
    end

    def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.fish = BCrypt::Engine.hash_secret(password, self.salt)
      end
    end

    def capitalize_names
      ['first_name', 'last_name'].each do |name|
        self.attributes[name] = self.attributes[name].capitalize
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @users = User.all.entries
    if params[:status] == "vet"
      @users = User.where(:status => "vet")
    elsif params[:status] == "rookie"
      @users = User.where(:status => "rookie")
    else
      @users = User.all.entries
    end

  end

  def new
    @user = User.new
  end

  def create
    @user = User.register_user (user_params)
    log_user_in (@user)

  end

  def show
   @user = User.find_by_id( params[:id] )
  end

  def edit
    @user = User.find_by_id( params[:id] )
  end

  def update
    @user = User.find_by_id( params[:id] )
    @user.update (user_params)
    render :show
  end

  def destroy
  end
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :status, :image)
  end

  def user_params_for_edit
    params.require(:user).permit(:first_name, :last_name, :email, :status)
  end

  def avatar
    content = @user.avatar.read
    if stale?(etag: content, last_modified: @user.updated_at.utc, public: true)
      send_data content, type: @user.avatar.file.content_type, disposition: "inline"
      expires_in 0, public: true
    end
  end

end

app/views/users/edit.slim
= form_for @user, :html => { :multipart => true} do |f|
  
  fieldset

    legend.legend Join the squad! 

    .form-group
      = f.label :first_name, class: "sr-only"
      = f.text_field :first_name, class: "form-control", placeholder: "first name"

    .form-group
      = f.label :last_name, class: "sr-only"
      = f.text_field :last_name, class: "form-control", placeholder: "last name"

    .form-group
      = f.label :email, class: "sr-only"
      = f.text_field :email, class: "form-control", placeholder: "email address"

    .form-group
      = f.label :status, class: "sr-only"
      = f.select :status, [["Vet"], ["Rookie"]], class: "form-control"

    .form-group
      =f.submit "Save", class: "btn btn-success btn-lg"

app/views/users/index.html.slim
sidebar.navbar-fixed-top.view-members-navbar
  .container.navbar-container.view-members-container
    ul.view-members-options.list-unstyled.list-inline
      li.squad-link.1.col-md-4 = link_to "All", users_path
      li.squad-link.2.col-md-4 = link_to "Vets", users_path(:status => "vet" )
      li.squad-link.3.col-md-4 = link_to "Rookies", users_path(:status => "rookie" )


.members-list.container
  .row
    - @users.each do |member|
      .face-wrapper.face.col-md-4
        .picture.img-responsive = image_tag member.image_url.to_s 
        .more-info
          .name = link_to "#{member.first_name} #{member.last_name}", user_path(member)
          .status = member.status
          
        

app/views/users/new.html.slim
= form_for @user, :html => { :multipart => true} do |f|
  
  fieldset

    legend.legend Join the squad! 

    .form-group
      = f.label :first_name, class: "sr-only"
      = f.text_field :first_name, class: "form-control", placeholder: "first name"

    .form-group
      = f.label :last_name, class: "sr-only"
      = f.text_field :last_name, class: "form-control", placeholder: "last name"

    .form-group
      = f.label :email, class: "sr-only"
      = f.text_field :email, class: "form-control", placeholder: "email address"
    
    .form-group
      = f.label :password, class: "sr-only"
      = f.password_field :password, class: "form-control", placeholder: "password"

    .form-group
      = f.label :status, "Status"
      = f.select :status, [["Vet"], ["Rookie"]], class: "form-control"


    .form-group.uploadpathdiv
      = f.label :image, "Upload a profile picture:"
      = f.file_field :image
    /   input.uploadpath name="path" type="text" /
    /   img src="/themes/scaccarium/images/button-upload.png" /
    /   img src="/themes/scaccarium/images/button-browse.png" /


    .form-group
      =f.submit "Register", class: "btn btn-success btn-lg"
      / id: "registration-form"
 

app/views/users/show.html.slim
.info
	h1.member_name
	  = " #{@user.first_name} #{@user.last_name}"

	.status
    = "#{@user.status}"

	.email
    = "#{@user.email}"
	
	.modify-user
    = link_to "Edit", edit_user_url, class: "btn btn-default edit-link"