config/routes.rb
EMS::Application.routes.draw do

  resources :users
  resources :pcrs

  root 'site#index'

  get 'login' => 'session#new'
  post 'login'=> 'session#create'
  delete 'logout' => 'session#destroy'
  get 'logout' => 'session#destroy'

  get 'privacy' => 'site#privacy'
  get 'terms'=> 'site#terms'

  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  # get 'squad' => 'members#index'

  # get 'register' => 'members#new'
  # post 'register' => 'members#create'

  # get 'members/:user_id' => 'members#show', as: :member

  # get 'pcr' => 'pcr#index'

  # get 'pcr' => 'pcr#new'
  # post 'pcr' => 'pcr#create'


  # put 'squad/edit/:user_id' => 'members#update'
  # patch 'squad/edit/:user_id' => 'members#update'
  # delete 'squad/:user_id' => 'members#destroy'


  # resources :user do
  #   get :avatar, on: :member
  # end
 
end

app/models/pcr.rb
class Pcr

  include Mongoid::Document
  include Mongoid::Timestamps
  # include Mongoid::Attributes::Dynamic

  field :emt_1_last_name, type: String, default: ''
  field :emt_2_last_name, type: String, default: ''
  field :emt_3_last_name, type: String, default: ''

  field :incident_date, type: DateTime
  field :case_number, type: String

  field :on_scene, type: DateTime
  field :transition, type: DateTime
  field :depart_scene, type: DateTime
  field :dispatched, type: DateTime

  field :pt_last_name, type: String
  field :pt_first_name, type: String
  field :pt_middle_name, type: String
  field :pt_birthdate, type: DateTime
  field :pt_age, type: String
  field :pt_sex, type: String
  field :pt_address, type: String
  field :pt_student_id, type: String
  field :pt_telephone, type: String
  field :pt_city, type: String
  field :pt_state, type: String
  field :pt_zip, type:String

  # field :pt_med_history, type: Array
  # field :pt_medications, type: Array
  # field :suspect_etoh, type: Boolean
  # field :suspect_drug, type: Boolean
  # field :pt_allergies, type: Array

  # field :incident_location, type: String
  # field :cheif_complaint, type: String

  # field :vitals_time_1, type: Time
  # field :vitals_bp_1, type: String
  # field :vitals_pulse_1, type: String
  # field :vitals_resp_1, type: String
  # field :vitals_pulse_ox_1, type: String
  # field :vital_temp_1, type: String

  # field :vitals_time_2, type: Time
  # field :vitals_bp_2, type: String
  # field :vitals_pulse_2, type: String
  # field :vitals_resp_2, type: String
  # field :vitals_pulse_ox_2, type: String
  # field :vital_temp_2, type: String

  # field :glascow_eyes, type: Integer
  # field :glascow_verbal, type: Integer
  # field :glascow_motor, type: Integer
  # field :glascow_total, type: Integer

  # field :skin_color, type: String
  # field :skin_temp, type: String
  # field :skin_moisture, type: String
  # field :airway, type: String
  # field :breathing, type: String
  # field :pupils, type: String

  # field :secondary_head, type:String
  # field :secondary_neck, type:String
  # field :secondary_chest, type:String
  # field :secondary_lungs, type:String
  # field :secondary_abdomen, type:String
  # field :secondary_back, type:String
  # field :secondary_pelvis, type:String
  # field :secondary_extremities, type:String

  # field :pt_disposition, type: String
  field :history_present_illness, type: String

  # field :med_direction_contact, type: Boolean
  # field :med_advisor, type: String
  # field :emt_caller, type: String
  # field :time_med_called, type: Time
  # field :med_advice_given, type: String

  # field :transport_destination, type: String
  # field :transport_by, type: String


  validates :case_number, presence: true, uniqueness: {case_sensitive: false}
  validates :emt_1_last_name, presence: true
  validates :emt_2_last_name, presence: true
  validates :emt_3_last_name, presence: true
  validates :pt_last_name, presence: true
  validates :pt_first_name, presence: true
  validates :history_present_illness, presence: true

  def self.create_pcr (params)
      pcr = Pcr.create (params)
      pcr if pcr
  end

  def self.find_by_id id
    if pcr = Pcr.find_by({:id => id})
    end
    pcr
  end


end

app/controllers/pcrs_controller.rb
class PcrsController < ApplicationController

  def index
    @pcrs = Pcr.all.entries
  end

  def new
    # @users = User.all.entries
    @pcr = Pcr.new
    @emt_1_options = User.options_for_emt_vet
    @emt_rookie_options = User.options_for_emt_rookie

  end

  def create
    # @pcr = Pcr.find_by(params[:id])
    @pcr = Pcr.create_pcr (pcr_params)
    redirect_to pcrs_url
  end

  def edit
    @pcr = Pcr.find_by_id ( params[:id] )
  end

  def update
    @pcr = Pcr.find_by_id( params[:id] )
    @pcr.update (pcr_params)
    redirect_to pcrs_url
  end
    

  def pcr_params
    params.require(:pcr).permit(:case_number, :emt_1_last_name, :emt_2_last_name, :emt_3_last_name, :incident_date, :on_scene, :transition, :depart_scene, :dispatched, :pt_last_name, :pt_first_name, :pt_middle_name, :pt_birthdate, :pt_age, :pt_sex, :pt_address, :pt_student_id, :pt_telephone, :pt_city, :pt_state, :pt_zip, :history_present_illness)
  end


end

app/views/pcrs/edit.html.slim
= form_for @pcr, html: { class: 'form-horizontal', :multipart => true } do |f|
  
  fieldset.container
    .row
      legend.pcr-legend Fill out incident information below:
    
    .row

      .form-group.col-md-6
        = f.label :case_number, 'Case Number'
        = f.text_field :case_number, class: "form-control"
      
    .row


      .form-group.col-md-8
        = f.label :incident_date, 'Incident Date/Time'
        / = f.text_field :incident_date, class: "form-control", id: "datetimepicker"
        = f.datetime_local_field :incident_date, class: "form-control"

      .form-group.col-md-8
        = f.label :on_scene, 'On Scene'
        = f.datetime_local_field :on_scene, class: "form-control"

      .form-group.col-md-8
        = f.label :transition, 'Transition'
        = f.datetime_local_field :transition, class: "form-control"

      .form-group.col-md-8
        = f.label :depart_scene, 'Depart Scene'
        = f.datetime_local_field :depart_scene, class: "form-control"

      .form-group.col-md-10
        = f.label :dispatched, 'Dispatched'
        = f.datetime_local_field :dispatched, class: "form-control"


      .form-group.col-md-4
        = f.label :pt_last_name, 'Last Name'
        = f.text_field :pt_last_name, class: "form-control"

      .form-group.col-md-4
        = f.label :pt_first_name, 'First Name'
        = f.text_field :pt_first_name, class: "form-control"

      .form-group.col-md-2
        = f.label :pt_middle_name, 'Middle Name'
        = f.text_field :pt_middle_name, class: "form-control"

      .form-group.col-md-8
        = f.label :pt_birthdate, 'Birthdate'
        = f.datetime_local_field :pt_birthdate, class: "form-control"
      
      .form-group.col-md-6
        = f.label :pt_age, 'Age'
        = f.text_field :pt_age, :class => "form-control"

      .form-group.col-md-6 
        = f.label :pt_student_id, 'Student ID'
        = f.text_field :pt_student_id, class: "form-control"

      .form-group.col-md-8 
        = f.label :pt_sex, 'Sex'
        = f.select :pt_sex, [['Female'], ['Male'], ['Other']], {}, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_telephone, 'Telephone'
        = f.text_field :pt_telephone, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_address, 'Address'
        = f.text_field :pt_address, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_city, 'City'
        = f.text_field :pt_city, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_state, 'State'
        = f.text_field :pt_state, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_zip, 'Zip Code'
        = f.text_field :pt_zip, class: "form-control"

    .row.col-md-6 

      .form-group
        = f.label :history_present_illness, 'History of Present Illness'
        = f.text_area :history_present_illness, placeholder: "Please give a description of the patient, incident, and care given.", class: "textinput"

      .form-group
        =f.submit "Save", class: "btn btn-success btn-lg"

app/views/pcrs/index.html.slim
.create-new = link_to "New PCR", new_pcr_url, method: :get, class: "btn btn-default create-pcr-link"

.pcr-list
  - @pcrs.each do |pcr|
      .pcr-info
      	.case-number = " Incident Number: #{pcr.case_number}"
        .name = "Patient Name: #{pcr.pt_last_name}, #{pcr.pt_first_name}"
        .emt = "EMT 1 (Vet): #{pcr.emt_1_last_name}"
        .emt = "EMT 2 (Rookie): #{pcr.emt_2_last_name}"
        .emt = "EMT 3 (Rookie): #{pcr.emt_3_last_name}"
        .edit = link_to "Edit", edit_pcr_url(pcr.id), class: "btn btn-default edit-link" 

app/views/pcrs/new.html.slim
= form_for @pcr, html: { class: 'form-horizontal', :multipart => true } do |f|
  
  fieldset.container
    .row
      legend.pcr-legend Fill out incident information below:
    
    .row

      .form-group.col-md-6
        = f.label :case_number, 'Case Number'
        = f.text_field :case_number, class: "form-control"
      
    .row

      .form-group.col-md-8
        = f.label :emt_1_last_name, "EMT 1 (Vet)"
        = f.select :emt_1_last_name, @emt_1_options, :class => "form-control"

      .form-group.col-md-8
        = f.label :emt_2_last_name, "EMT 2 (Rookie)"
        = f.select :emt_2_last_name, @emt_rookie_options, :class => "form-control"

      .form-group.col-md-8
        = f.label :emt_3_last_name, "EMT 3 (Rookie)"
        = f.select :emt_3_last_name, @emt_rookie_options, :class => "form-control"


      .form-group.col-md-8
        = f.label :incident_date, 'Incident Date/Time'
        / = f.text_field :incident_date, class: "form-control", id: "datetimepicker"
        = f.datetime_local_field :incident_date, class: "form-control"

      .form-group.col-md-8
        = f.label :on_scene, 'On Scene'
        = f.datetime_local_field :on_scene, class: "form-control"

      .form-group.col-md-8
        = f.label :transition, 'Transition'
        = f.datetime_local_field :transition, class: "form-control"

      .form-group.col-md-8
        = f.label :depart_scene, 'Depart Scene'
        = f.datetime_local_field :depart_scene, class: "form-control"

      .form-group.col-md-10
        = f.label :dispatched, 'Dispatched'
        = f.datetime_local_field :dispatched, class: "form-control"


      .form-group.col-md-4
        = f.label :pt_last_name, 'Last Name'
        = f.text_field :pt_last_name, class: "form-control"

      .form-group.col-md-4
        = f.label :pt_first_name, 'First Name'
        = f.text_field :pt_first_name, class: "form-control"

      .form-group.col-md-2
        = f.label :pt_middle_name, 'Middle Name'
        = f.text_field :pt_middle_name, class: "form-control"

      .form-group.col-md-8
        = f.label :pt_birthdate, 'Birthdate'
        = f.datetime_local_field :pt_birthdate, class: "form-control"
      
      .form-group.col-md-6
        = f.label :pt_age, 'Age'
        = f.text_field :pt_age, :class => "form-control"

      .form-group.col-md-6 
        = f.label :pt_student_id, 'Student ID'
        = f.text_field :pt_student_id, class: "form-control"

      .form-group.col-md-8 
        = f.label :pt_sex, 'Sex'
        = f.select :pt_sex, [['Female'], ['Male'], ['Other']], {}, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_telephone, 'Telephone'
        = f.text_field :pt_telephone, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_address, 'Address'
        = f.text_field :pt_address, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_city, 'City'
        = f.text_field :pt_city, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_state, 'State'
        = f.text_field :pt_state, class: "form-control"

      .form-group.col-md-6 
        = f.label :pt_zip, 'Zip Code'
        = f.text_field :pt_zip, class: "form-control"

    .row.col-md-6 

      .form-group
        = f.label :history_present_illness, 'History of Present Illness'
        = f.text_area :history_present_illness, placeholder: "Please give a description of the patient, incident, and care given.", class: "textinput"

      .form-group
        =f.submit "Save", class: "btn btn-success btn-lg"