config/routes.rb
EMS::Application.routes.draw do

  resources :users
  resources :pcrs

  root 'site#index'

  get 'login' => 'session#new'
  post 'login'=> 'session#create'
  delete 'logout' => 'session#destroy'
  get 'logout' => 'session#destroy'

  get 'privacy' => 'site#privacy'
  get 'terms'=> 'site#terms'

  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  # get 'squad' => 'members#index'

  # get 'register' => 'members#new'
  # post 'register' => 'members#create'

  # get 'members/:user_id' => 'members#show', as: :member

  # get 'pcr' => 'pcr#index'

  # get 'pcr' => 'pcr#new'
  # post 'pcr' => 'pcr#create'


  # put 'squad/edit/:user_id' => 'members#update'
  # patch 'squad/edit/:user_id' => 'members#update'
  # delete 'squad/:user_id' => 'members#destroy'


  # resources :user do
  #   get :avatar, on: :member
  # end
 
end

app/views/layouts/application.html.slim
doctype html
html
  head
    link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" media= "all" rel= "stylesheet"
    link href='http://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    title = link_to "Santa Clara University EMS", root_url, method: :get

  body

    #wrap

      header.navbar.navbar-fixed-top role="navigation"
        .container.nav-container
          .header-logo
            .pull-right.logout-link
              = link_to "Log Out", logout_url, method: :delete, class: "btn btn-danger logout-link" if current_user
            h1.top-header-brand Santa Clara University EMS
          .container.inner-nav-container
            ul.nav-links.list-unstyled.list-inline
              .header-link.0.col-md-6 = link_to "Squad", users_url, method: :get 
              .header-link.2.col-md-6  = link_to "PCR", pcrs_url, method: :get

      main#main.container role="main"
        == yield

      footer#footer.footer
        .container
          .row
            p.text-muted.credit
              = link_to "Privacy Policy", privacy_url
              |  &bull;
              = link_to " Terms of Use", terms_url
              |  &bull;
              |  © 2014 annie cheung

      == flash_noty_script_tag